source "${LDK_DIR}/p3509-a02-p3767-0000.conf"

OVERLAY_DTB_FILE+=",tegra234-p3767-echopilot-branding.dtbo,tegra234-p3767-disable-display.dtbo,tegra234-p3767-enable-serial.dtbo";

# EchopPilot AI is only capable of 25W DC-DC buck conversion on the 5V rail powering the Jetson SOM
# So only the Jetson Nano (0003, 0004, 0005) Super overlay is enabled, not NX which can draw up to 40W with the Super overlay
p3767_nano_only_super_overlay()
{
	if [ "${board_sku}" = "0003" ]; then
		BPFDTB_FILE="tegra234-bpmp-3767-0003-3768-super.dtb";
		DTB_FILE="tegra234-p3768-0000+p3767-0003-nv-super.dtb";
	elif [ "${board_sku}" = "0004" ]; then
		BPFDTB_FILE="tegra234-bpmp-3767-0004-3768-super.dtb";
		DTB_FILE="tegra234-p3768-0000+p3767-0004-nv-super.dtb";
	elif [ "${board_sku}" = "0005" ]; then
		BPFDTB_FILE="tegra234-bpmp-3767-0003-3768-super.dtb";
		DTB_FILE="tegra234-p3768-0000+p3767-0005-nv-super.dtb";
	fi

	TBCDTB_FILE="${DTB_FILE}";
}

update_flash_args()
{
	update_flash_args_common
	p3767_nano_only_super_overlay
}